import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { Lato } from "next/font/google";
import "./globals.css";



const latoFont = Lato({
  variable: ['--font-lato-regular', '--font-lato-bold', '--font-lato-black'],
  weight: ['100', '300', '400', '700', '900'],
  subsets: ["latin"],
  style: 'normal'
})



export const metadata = {
  title: "MaohibTech - A ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${latoFont.variable} antialiased`}
      >
        <Header />
        <main className="container mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
